import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const URL=(Deno.env.get("SUPABASE_URL")??"").replace(/\/$/,""), KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const GRAPH=Deno.env.get("META_GRAPH_VERSION")??"v26.0";
const ROLES=new Set(["super_admin","admin","content_manager"]);
function json(b:Record<string,unknown>,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","access-control-allow-origin":"https://hub.relaxfixuae.com","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS"}})}
function bearer(r:Request){const h=r.headers.get("authorization")??"";return h.startsWith("Bearer ")?h.slice(7):""}
async function hmac(token:string){const secret=(Deno.env.get("META_APP_SECRET")??"").trim();if(!secret)return "";const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const s=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(token));return Array.from(new Uint8Array(s),b=>b.toString(16).padStart(2,"0")).join("")}
async function staff(s:any,t:string){const a=await s.auth.getUser(t);if(a.error||!a.data.user)return null;const p=await s.from("staff_profiles").select("id,role,active").eq("id",a.data.user.id).maybeSingle();return p.data?.active&&ROLES.has(String(p.data.role))?String(a.data.user.id):null}
async function graph(id:string,token:string,fields:string){const q=new URLSearchParams({access_token:token,fields});const proof=await hmac(token);if(proof)q.set("appsecret_proof",proof);const r=await fetch(`https://graph.facebook.com/${GRAPH}/${encodeURIComponent(id)}?${q}`);const b=await r.json().catch(()=>null) as any;if(!r.ok||b?.error)return null;return b}
async function mark(s:any,provider:string,staffId:string,label:string,metadata:Record<string,unknown>={}){const now=new Date().toISOString();const up=await s.from("staff_integrations").upsert({provider,connection_method:"oauth",status:"connected",display_name:provider==="meta_whatsapp"?"WhatsApp / Meta":provider==="instagram"?"Instagram":"Facebook",account_label:label,secret_hint:"Server-side Meta credential",metadata:{...metadata,verifiedExternally:true},connected_by:staffId,connected_at:now,last_tested_at:now,last_error_code:null,updated_at:now},{onConflict:"provider"}).select("id").single();if(up.error)return false;await s.from("audit_logs").insert({actor_id:staffId,actor_type:"user",action:"integration_tested",entity_type:"staff_integration",entity_id:up.data.id,detail:{provider,result:"external_verified",accountLabel:label}});return true}
Deno.serve(async(r)=>{if(r.method==="OPTIONS")return new Response(null,{status:204});if(r.method!=="POST")return json({success:false,code:"METHOD_NOT_ALLOWED"},405);if(!URL||!KEY)return json({success:false,code:"SERVER_MISCONFIGURED"},500);const s=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});const id=await staff(s,bearer(r));if(!id)return json({success:false,code:"STAFF_ACCESS_DENIED"},403);const b=await r.json().catch(()=>({}));const p=String(b.provider??"");if(p==="facebook"){
const row=await s.from("staff_integrations").select("id").eq("provider","facebook").maybeSingle();
if(row.error||!row.data?.id)return json({success:false,code:"META_NOT_CONNECTED",provider:p},424);
const sec=await s.from("staff_integration_secrets").select("secret_value").eq("integration_id",row.data.id).maybeSingle();
const token=String(sec.data?.secret_value??"").trim();
const page=(Deno.env.get("FACEBOOK_PAGE_ID")??"1164107840123575").trim();
if(!token||!page)return json({success:false,code:"META_NOT_CONFIGURED",provider:p},424);
const x=await graph(page,token,"id,name");
if(!x)return json({success:false,code:"META_EXTERNAL_TEST_FAILED",provider:p},502);
if(!await mark(s,p,id,String(x.name??x.id),{facebookPageId:String(x.id)}))return json({success:false,code:"STATUS_STORE_FAILED"},500);
return json({success:true,provider:p,status:"connected",accountLabel:String(x.name??x.id)});
}
if(p==="instagram"){const token=(Deno.env.get("INSTAGRAM_ACCESS_TOKEN")??"").trim(),account=(Deno.env.get("INSTAGRAM_ACCOUNT_ID")??"").trim();if(!token||!account)return json({success:false,code:"META_NOT_CONFIGURED",provider:p},424);const x=await graph(account,token,"id,username");if(!x)return json({success:false,code:"META_EXTERNAL_TEST_FAILED",provider:p},502);if(!await mark(s,p,id,String(x.username??x.id),{instagramAccountId:String(x.id)}))return json({success:false,code:"STATUS_STORE_FAILED"},500);return json({success:true,provider:p,status:"connected",accountLabel:String(x.username??x.id)});}
if(p==="meta_whatsapp"){const token=(Deno.env.get("WHATSAPP_CLOUD_ACCESS_TOKEN")??Deno.env.get("META_WHATSAPP_ACCESS_TOKEN")??"").trim(),phone=(Deno.env.get("WHATSAPP_PHONE_NUMBER_ID")??"").trim();if(!token||!phone)return json({success:false,code:"META_NOT_CONFIGURED",provider:p},424);const x=await graph(phone,token,"id,display_phone_number,verified_name");if(!x)return json({success:false,code:"META_EXTERNAL_TEST_FAILED",provider:p},502);if(!await mark(s,p,id,String(x.display_phone_number??x.verified_name??x.id),{phoneNumberId:String(x.id)}))return json({success:false,code:"STATUS_STORE_FAILED"},500);return json({success:true,provider:p,status:"connected",accountLabel:String(x.display_phone_number??x.verified_name??x.id)});}
return json({success:false,code:"UNSUPPORTED_PROVIDER"},400);});