import { useMemo } from "react";
import { automationAttentionLabel, automationStateLabel, countActiveAutomationStates, formatAutomationValue, summarizeAutomationStatus } from "./automation-status";
import { useLanguage } from "./i18n";
import "./integrations.css";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export default function AutomationsView({ value, onOpenQueue, onOpenContent }: { value: JsonValue; onOpenQueue: () => void; onOpenContent: () => void }) {
  const { language, t } = useLanguage();
  const copy = language === "ar" ? {
    bannerTitle: "حالة الأتمتة للقراءة فقط", bannerText: "تعكس آخر لقطة مسجلة لحالة الأتمتة من الخادم؛ لا يتم تنفيذ أي إجراء أتمتة من هذه الشاشة.", empty: "لا توجد بيانات حالة أتمتة حاليًا.", recordLabel: "سجل", summaryTitle: "لقطة الأتمتة", latestSnapshot: "آخر نتيجة من RPC", activeLabel: "العمل النشط", activeHelp: "في الانتظار أو قيد التنفيذ أو إعادة المحاولة", attentionLabel: "انتباه المالك", attentionHelp: "حالات فشل أو توقف مسجلة", readinessLabel: "جاهزية النشر", readinessHelp: "تظهر فقط إذا سجلها المصدر", notAvailable: "غير مسجل", statusEyebrow: "حالات التنفيذ", statusTitle: "أعداد الحالات المسجلة", batchEyebrow: "الدفعة الحالية", batchTitle: "سياق الدفعة والتوليد", batchUnavailable: "لم تتضمن آخر لقطة دفعة حالية.", batchIdLabel: "معرّف الدفعة", batchStateLabel: "حالة الدفعة", batchItemsLabel: "العناصر", providerLabel: "المزود", executionEyebrow: "تفاصيل التنفيذ", executionTitle: "آخر تنفيذ مسجل", lastRunLabel: "آخر تشغيل", nextRunLabel: "التشغيل التالي", attemptLabel: "المحاولة", errorLabel: "آخر خطأ", attentionEyebrow: "انتباه قابل للإجراء", attentionTitle: "مشكلات مسجلة للفحص", noAttention: "لا توجد سجلات فاشلة أو متوقفة أو ملغاة أو بها خطأ في هذه اللقطة.",
  } : {
    bannerTitle: "Read-only automation status", bannerText: "Reflects the latest recorded snapshot; no action is triggered here.", empty: "No automation status yet.", recordLabel: "Record", summaryTitle: "Automation snapshot", latestSnapshot: "Latest RPC result", activeLabel: "Active work", activeHelp: "Queued, processing, or retrying", attentionLabel: "Owner attention", attentionHelp: "Recorded failures or stops", readinessLabel: "Publishing readiness", readinessHelp: "Only shown when recorded by the source", notAvailable: "Not recorded", statusEyebrow: "Execution states", statusTitle: "Recorded state counts", batchEyebrow: "Current batch", batchTitle: "Batch and generation context", batchUnavailable: "No current batch was included in the latest snapshot.", batchIdLabel: "Batch ID", batchStateLabel: "Batch state", batchItemsLabel: "Items", providerLabel: "Provider", executionEyebrow: "Execution details", executionTitle: "Latest recorded execution", lastRunLabel: "Last run", nextRunLabel: "Next run", attemptLabel: "Attempt", errorLabel: "Last error", attentionEyebrow: "Actionable attention", attentionTitle: "Recorded issues to inspect", noAttention: "No failed, dead, cancelled, or errored record was included in this snapshot.",
  };
  const snapshot = useMemo(() => summarizeAutomationStatus(value), [value]);
  const openQueue = language === "ar" ? "فتح طابور العمليات" : "Open operations queue";
  const openContent = language === "ar" ? "فتح مصنع المحتوى" : "Open Content Factory";
  const statusEntries = (["queued", "processing", "retrying", "failed", "completed", "cancelled", "dead"] as const).filter((status) => snapshot.states[status] > 0);
  return <div className="automations-view">
    <div className="operations-boundary"><div><strong>{copy.bannerTitle}</strong><p>{copy.bannerText}</p></div><div className="automation-actions"><button type="button" onClick={onOpenQueue}>{openQueue}</button><button type="button" onClick={onOpenContent}>{openContent}</button></div></div>
    {!snapshot.sourceAvailable ? <p className="muted">{copy.empty}</p> : <>
      <section className="automation-summary-grid" aria-label={copy.summaryTitle}>
        <article><span>{copy.recordLabel}</span><strong>{snapshot.recordCount}</strong><small>{copy.latestSnapshot}</small></article>
        <article><span>{copy.activeLabel}</span><strong>{countActiveAutomationStates(snapshot)}</strong><small>{copy.activeHelp}</small></article>
        <article className={snapshot.attention.length > 0 ? "attention" : ""}><span>{copy.attentionLabel}</span><strong>{snapshot.attention.length}</strong><small>{copy.attentionHelp}</small></article>
        <article><span>{copy.readinessLabel}</span><strong>{snapshot.publishingReadiness ?? copy.notAvailable}</strong><small>{copy.readinessHelp}</small></article>
      </section>
      {statusEntries.length > 0 && <section className="automation-status-list" aria-labelledby="automation-status-heading"><header><p>{copy.statusEyebrow}</p><h2 id="automation-status-heading">{copy.statusTitle}</h2></header><div className="automation-status-grid">{statusEntries.map((status) => <article key={status} className={`job-status-card job-${status}`}><span>{automationStateLabel(status, language)}</span><strong>{snapshot.states[status]}</strong></article>)}</div></section>}
      <section className="automation-detail-grid"><article><p>{copy.batchEyebrow}</p><h2>{copy.batchTitle}</h2>{snapshot.currentBatch ? <dl className="record"><dt>{copy.batchIdLabel}</dt><dd>{snapshot.currentBatch.id ?? copy.notAvailable}</dd><dt>{copy.batchStateLabel}</dt><dd>{automationStateLabel(snapshot.currentBatch.state, language)}</dd><dt>{copy.batchItemsLabel}</dt><dd>{snapshot.currentBatch.itemCount ?? copy.notAvailable}</dd><dt>{copy.providerLabel}</dt><dd>{snapshot.currentBatch.provider ?? copy.notAvailable}</dd></dl> : <p className="muted">{copy.batchUnavailable}</p>}</article><article><p>{copy.executionEyebrow}</p><h2>{copy.executionTitle}</h2><dl className="record"><dt>{copy.lastRunLabel}</dt><dd>{formatAutomationValue(snapshot.execution.lastRun, language)}</dd><dt>{copy.nextRunLabel}</dt><dd>{formatAutomationValue(snapshot.execution.nextRun, language)}</dd><dt>{copy.attemptLabel}</dt><dd>{snapshot.execution.attempt ?? copy.notAvailable}</dd><dt>{copy.errorLabel}</dt><dd>{snapshot.execution.lastError ?? copy.notAvailable}</dd></dl></article></section>
      <section className="automation-attention" aria-labelledby="automation-attention-heading"><header><div><p>{copy.attentionEyebrow}</p><h2 id="automation-attention-heading">{copy.attentionTitle}</h2></div><span>{snapshot.attention.length}</span></header>{snapshot.attention.length === 0 ? <p className="muted">{copy.noAttention}</p> : <div className="automation-attention-list">{snapshot.attention.map((item) => <article key={item.id}><div><strong>{item.title}</strong><p>{item.detail}</p></div><button type="button" onClick={item.action === "open_content" ? onOpenContent : onOpenQueue}>{automationAttentionLabel(item.action, language)}</button></article>)}</div>}</section>
    </>}
  </div>;
}
