import { useEffect, useState } from "react";
import { ChevronLeft, Copy, ExternalLink, File as DriveFileIcon, Folder, Loader2, LogIn, Plus, RefreshCw, Trash2, Upload, X } from "lucide-react";
import "./google-drive-manager.css";

type DriveItem = { id: string; name: string; mimeType: string; size?: string; webViewLink?: string };
type TokenClient = { requestAccessToken: () => void };
declare global { interface Window { google?: { accounts?: { oauth2?: { initTokenClient: (config: { client_id: string; scope: string; callback: (response: { access_token?: string; error?: string }) => void }) => TokenClient } } } } }

const CLIENT_ID = (import.meta.env.VITE_GOOGLE_DRIVE_CLIENT_ID ?? "").trim();
const SOURCE = (import.meta.env.VITE_MASSIVE_ARCHIVE_DRIVE_FOLDER_URL ?? "").trim();
const ROOT_ID = SOURCE.match(/\/folders\/([a-zA-Z0-9_-]+)/)?.[1] ?? (/^[a-zA-Z0-9_-]{10,}$/.test(SOURCE) ? SOURCE : "");
const DRIVE_SCOPE = "https://www.googleapis.com/auth/drive";
const FOLDER_MIME = "application/vnd.google-apps.folder";

function ensureGoogleScript() { if (typeof document === "undefined" || document.querySelector('script[data-google-drive-identity="true"]')) return; const script = document.createElement("script"); script.src = "https://accounts.google.com/gsi/client"; script.async = true; script.defer = true; script.dataset.googleDriveIdentity = "true"; document.head.appendChild(script); }
async function driveFetch<T>(token: string, path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`https://www.googleapis.com/drive/v3/${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, Accept: "application/json", ...(init.headers ?? {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(typeof body?.error?.message === "string" ? body.error.message : `DRIVE_HTTP_${response.status}`); } return response.json() as Promise<T>; }

export default function GoogleDriveManagerView() {
  const [token, setToken] = useState(""); const [items, setItems] = useState<DriveItem[]>([]); const [folderId, setFolderId] = useState(ROOT_ID); const [stack, setStack] = useState<{ id: string; name: string }[]>(ROOT_ID ? [{ id: ROOT_ID, name: "Massive Archive" }] : []); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [newName, setNewName] = useState(""); const [newFolderOpen, setNewFolderOpen] = useState(false);
  useEffect(() => { ensureGoogleScript(); }, []);
  const configured = Boolean(CLIENT_ID && ROOT_ID);
  const load = async (id = folderId) => { if (!token || !id) return; setBusy(true); setMessage(""); try { const q = encodeURIComponent(`'${id}' in parents and trashed = false`); const result = await driveFetch<{ files?: DriveItem[] }>(token, `files?q=${q}&pageSize=100&orderBy=folder,name&fields=files(id,name,mimeType,size,webViewLink)`); setItems(result.files ?? []); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر قراءة Google Drive"); } finally { setBusy(false); } };
  useEffect(() => { if (token) void load(); }, [token, folderId]);
  const connect = () => { if (!CLIENT_ID) { setMessage("يلزم VITE_GOOGLE_DRIVE_CLIENT_ID أولًا."); return; } if (!window.google?.accounts?.oauth2) { ensureGoogleScript(); setMessage("جاري تحميل اتصال Google. اضغط الاتصال مرة أخرى بعد لحظات."); return; } const client = window.google.accounts.oauth2.initTokenClient({ client_id: CLIENT_ID, scope: DRIVE_SCOPE, callback: (r) => { if (r.error || !r.access_token) { setMessage(r.error ?? "تعذر الاتصال بـGoogle"); return; } setToken(r.access_token); } }); client.requestAccessToken(); };
  const openFolder = (item: DriveItem) => { setStack((s) => [...s, { id: item.id, name: item.name }]); setFolderId(item.id); };
  const back = () => { if (stack.length <= 1) return; const next = stack.slice(0, -1); setStack(next); setFolderId(next.at(-1)!.id); };
  const createFolder = async () => { const name = newName.trim(); if (!name || !token || !folderId) return; setBusy(true); try { await driveFetch(token, "files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, mimeType: FOLDER_MIME, parents: [folderId] }) }); setNewName(""); setNewFolderOpen(false); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر إنشاء المجلد"); } finally { setBusy(false); } };
  const rename = async (item: DriveItem) => { const name = window.prompt("الاسم الجديد", item.name)?.trim(); if (!name || name === item.name || !token) return; setBusy(true); try { await driveFetch(token, `files/${encodeURIComponent(item.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر إعادة التسمية"); } finally { setBusy(false); } };
  const trash = async (item: DriveItem) => { if (!token || !window.confirm(`نقل «${item.name}» إلى سلة المهملات؟`)) return; setBusy(true); try { await driveFetch(token, `files/${encodeURIComponent(item.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ trashed: true }) }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر الحذف"); } finally { setBusy(false); } };
  const copyLink = async (item: DriveItem) => { const link = item.webViewLink ?? `https://drive.google.com/open?id=${item.id}`; try { await navigator.clipboard.writeText(link); setMessage("تم نسخ الرابط"); } catch { setMessage(link); } };
  const upload = async (file: globalThis.File) => { if (!token || !folderId) return; setBusy(true); try { const metadata = new Blob([JSON.stringify({ name: file.name, parents: [folderId] })], { type: "application/json" }); const body = new FormData(); body.append("metadata", metadata); body.append("file", file); const response = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,webViewLink", { method: "POST", headers: { Authorization: `Bearer ${token}` }, body }); if (!response.ok) throw new Error(`DRIVE_UPLOAD_HTTP_${response.status}`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر رفع الملف"); } finally { setBusy(false); } };
  if (!configured) return <section className="drive-manager"><div className="drive-manager-notice"><h2>Google Drive Manager</h2><p>الموديول معزول وآمن، لكنه لن يتصل بـGoogle قبل ضبط Client ID ورابط مجلد الأرشيف.</p><code>VITE_GOOGLE_DRIVE_CLIENT_ID</code></div></section>;
  return <section className="drive-manager"><header className="drive-manager-header"><div><span className="drive-kicker">Massive Archive</span><h2>Google Drive Manager</h2><p>إدارة مباشرة للملفات والمجلدات بدون نسخ الأرشيف إلى Supabase.</p></div>{!token ? <button className="drive-primary" onClick={connect}><LogIn size={17}/> الاتصال بـGoogle Drive</button> : <button className="drive-secondary" onClick={() => void load()} disabled={busy}><RefreshCw size={17}/> تحديث</button>}</header>{!token ? <div className="drive-manager-notice"><p>رمز Google يبقى في ذاكرة الصفحة فقط ولا يتم حفظه في localStorage أو sessionStorage.</p></div> : <><div className="drive-toolbar"><button onClick={back} disabled={stack.length <= 1}><ChevronLeft size={17}/> رجوع</button><strong>{stack.at(-1)?.name ?? "Massive Archive"}</strong><button onClick={() => setNewFolderOpen(true)}><Plus size={17}/> مجلد جديد</button><label className="drive-upload"><Upload size={17}/> رفع ملف<input type="file" onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file); e.currentTarget.value = ""; }}/></label></div>{newFolderOpen && <div className="drive-dialog"><input autoFocus value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="اسم المجلد"/><button onClick={() => void createFolder()} disabled={busy || !newName.trim()}>إنشاء</button><button onClick={() => setNewFolderOpen(false)}><X size={17}/></button></div>}{message && <div className="drive-message" role="status">{message}</div>}<div className="drive-list">{busy && <div className="drive-loading"><Loader2 className="spin" size={20}/> جاري التنفيذ…</div>}{!busy && items.length === 0 && <div className="drive-empty">المجلد فارغ.</div>}{items.map((item) => <article className="drive-row" key={item.id}><div className="drive-item-icon">{item.mimeType === FOLDER_MIME ? <Folder size={21}/> : <DriveFileIcon size={21}/>}</div><div className="drive-item-main"><strong>{item.name}</strong><small>{item.mimeType === FOLDER_MIME ? "مجلد" : item.size ? `${Number(item.size).toLocaleString()} bytes` : "ملف"}</small></div><div className="drive-actions">{item.mimeType === FOLDER_MIME && <button onClick={() => openFolder(item)}>فتح</button>}<button onClick={() => void rename(item)}>تعديل</button><button onClick={() => void copyLink(item)}><Copy size={16}/></button>{item.webViewLink && <a href={item.webViewLink} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/></a>}<button className="danger" onClick={() => void trash(item)}><Trash2 size={16}/></button></div></article>)}</div></>}</section>;
}
