/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBrainRouteImport } from './routes/api/brain'
import { Route as ApiCanvaRouteImport } from './routes/api/canva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainRoute = ApiBrainRouteImport.update({
  id: '/api/brain',
  path: '/api/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvaRoute = ApiCanvaRouteImport.update({
  id: '/api/canva',
  path: '/api/canva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/brain': typeof ApiBrainRoute
  '/api/canva': typeof ApiCanvaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/brain': typeof ApiBrainRoute
  '/api/canva': typeof ApiCanvaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/brain': typeof ApiBrainRoute
  '/api/canva': typeof ApiCanvaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/brain' | '/api/canva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/brain' | '/api/canva'
  id: '__root__' | '/' | '/api/brain' | '/api/canva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBrainRoute: typeof ApiBrainRoute
  ApiCanvaRoute: typeof ApiCanvaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain': {
      id: '/api/brain'
      path: '/api/brain'
      fullPath: '/api/brain'
      preLoaderRoute: typeof ApiBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canva': {
      id: '/api/canva'
      path: '/api/canva'
      fullPath: '/api/canva'
      preLoaderRoute: typeof ApiCanvaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBrainRoute: ApiBrainRoute,
  ApiCanvaRoute: ApiCanvaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
